blog_user_admin_user:
    resource: "@BlogUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

blog_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogUserBundle:Default:index }

login:
    pattern:   /login
    defaults: { _controller: BlogUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:  /logout

register:
    pattern:  /register
    defaults: { _controller: BlogUserBundle:Registration:register }

checkEmail:
    pattern:  /check-email

confirm:
    pattern:  /confirm/{token}

confirmed:
    pattern:  /confirmed
    defaults: { _controller: BlogUserBundle:Registration:confirmed }