blog_user_admin_user:
    resource: "@BlogUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

blog_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogUserBundle:Default:index }
