blog_user_admin_user:
    resource: "@BlogUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

blog_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogUserBundle:Default:index }

user_login:
    pattern:   /login
    defaults: { _controller: BlogUserBundle:Security:login }

user_login_check:
    pattern:   /login_check

user_logout:
    pattern:  /logout

user_register:
    pattern:  /register
    defaults: { _controller: BlogUserBundle:Registration:register }

user_checkEmail:
    pattern:  /check-email

user_confirm:
    pattern:  /confirm/{token}

user_confirmed:
    pattern:  /confirmed
    defaults: { _controller: BlogUserBundle:Registration:confirmed }
