Blog\AdminBundle\Entity\Settings:
    type: entity
    table: null
    repositoryClass: Blog\AdminBundle\Entity\SettingsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        body:
            type: text
        sidebarAbout:
            type: text
        metaName:
            type: string
            length: 255
        metaDescription:
            type: string
            length: 255
            nullable: true
        pages:
            type: string
            length: 255
            nullable: true
        adSpaceHorizontal:
            type: string
            length: 255
            nullable: true
        adSpaceVertical:
            type: string
            length: 255
            nullable: true
        github:
            type: string
            length: 255
            nullable: true
        twitter:
            type: string
            length: 255
            nullable: true
        facebook:
            type: string
            length: 255
            nullable: true
        linkedin:
            type: string
            lenght: 255
            nullable: true
    lifecycleCallbacks: {  }
