blog_admin_settings:
    resource: "@BlogAdminBundle/Resources/config/routing/settings.yml"
    prefix:   /settings

blog_admin_message:
    resource: "@BlogAdminBundle/Resources/config/routing/message.yml"
    prefix:   /message

blog_admin_tag:
    resource: "@BlogAdminBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

blog_admin_post:
    resource: "@BlogAdminBundle/Resources/config/routing/post.yml"
    prefix:   /post

blog_admin_homepage:
    path:     /dashboard
    defaults: { _controller: BlogAdminBundle:Default:index }

admin.login:
    pattern:   /login
    defaults: { _controller: BlogAdminBundle:Security:login }

admin.login_check:
    pattern:   /login_check

admin.logout:
    pattern:  /logout

admin.register:
    pattern:  /register
    defaults: { _controller: BlogAdminBundle:Registration:register }

checkEmail:
    pattern:  /check-email

confirm:
    pattern:  /confirm/{token}

confirmed:
    pattern:  /confirmed
    defaults: { _controller: BlogAdminBundle:Registration:confirmed }
