blog_main_homepage:
    path:     /
    defaults: { _controller: BlogMainBundle:Default:index }

blog_main_post:
    path:    /post/{id}
    defaults: { _controller: BlogMainBundle:Default:post }

blog_main_about:
    path:   /about
    defaults: { _controller: BlogMainBundle:Default:about }
