blog_main_homepage:
    path:     /{page}
    defaults: { _controller: BlogMainBundle:Default:index, page: 1 }
    requirements:
        page: \d+

blog_main_post:
    path:    /post/{id}
    defaults: { _controller: BlogMainBundle:Default:post }

blog_main_about:
    path:   /about
    defaults: { _controller: BlogMainBundle:Default:about }

blog_main_social_links:
    path:   /socialLinks
    defaults: { _controller: BlogMainBundle:Default:socialLinks }